name: chat
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.13
  firebase_core: ^2.25.2
  cloud_firestore: ^4.15.2
  firebase_database: ^10.4.3
  firebase_auth: ^4.20.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.0
  flutter_spinkit: ^5.2.1
  collection: ^1.18.0
  nb_utils: ^7.0.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
