// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUv7Y1h7hkFDPiXiw0Cdyxdr4dsxaB9BU',
    appId: '1:29460329775:web:195e694a309c88a53addda',
    messagingSenderId: '29460329775',
    projectId: 'litechat-add9c',
    authDomain: 'litechat-add9c.firebaseapp.com',
    storageBucket: 'litechat-add9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX38q_oF9WZuncm-k2rATZfuY7PisEXew',
    appId: '1:29460329775:android:626c9ced9c313d463addda',
    messagingSenderId: '29460329775',
    projectId: 'litechat-add9c',
    storageBucket: 'litechat-add9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD56yyfshz3vrZkQ2zazWAX7VZYk24RCKk',
    appId: '1:29460329775:ios:8fbeefcc070d2f3c3addda',
    messagingSenderId: '29460329775',
    projectId: 'litechat-add9c',
    storageBucket: 'litechat-add9c.appspot.com',
    iosBundleId: 'com.emantggw.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD56yyfshz3vrZkQ2zazWAX7VZYk24RCKk',
    appId: '1:29460329775:ios:872727d2816e01d73addda',
    messagingSenderId: '29460329775',
    projectId: 'litechat-add9c',
    storageBucket: 'litechat-add9c.appspot.com',
    iosBundleId: 'com.emantggw.chat.RunnerTests',
  );
}
